import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import realData from './realDecisionData'
import './App.css'

// Every decision, mandate, reason and latency below comes from the REAL engine,
// generated by demo-harness/export_ui_data.py over Viseca's own data pack.
// The previous build shipped invented purchases judged by a second decision
// engine written in JavaScript; none of what it showed came from the system
// being demoed. That is gone.

const API = 'http://127.0.0.1:8787'
const STAGE_MS = 700

const STAGES = [
  { key: 'instruction', label: 'Instruction' },
  { key: 'mandate', label: 'Mandate' },
  { key: 'checks', label: 'Checks' },
  { key: 'decision', label: 'Decision' },
]

const OUTCOME_LABEL = { approve: 'Approved', step_up: 'Ask you', decline: 'Declined' }

// Reason codes the engine emits -> how a non-technical reader should see them.
const REASON_META = {
  within_policy: ['Within policy', 'ok'],
  hard_rule_violation: ['Hard rule breached', 'fail'],
  rule_unverifiable: ['Rule could not be checked', 'warn'],
  mandate_not_active: ['Mandate not active', 'fail'],
  engine_error: ['Engine error - failed closed', 'fail'],
  merchant_category_mismatch: ['Wrong kind of merchant', 'fail'],
  lookalike_merchant: ['Lookalike seller', 'fail'],
  unfamiliar_merchant: ['Seller not used before', 'warn'],
  likely_duplicate: ['Looks like a repeat order', 'warn'],
  likely_retry: ['Retry of a declined order', 'ok'],
  fulfillment_mismatch: ['Return terms contradicted', 'fail'],
  fulfillment_unverifiable: ['Return terms unverifiable', 'warn'],
  suspected_injected_instructions: ['Injected text detected', 'warn'],
  attempt_burst: ['Burst of attempts', 'warn'],
  duplicate_delivery: ['Duplicate delivery', 'ok'],
}

function describeReason(code) {
  if (REASON_META[code]) return REASON_META[code]
  if (code.startsWith('uncertainty_policy:')) {
    return [`Uncertainty policy: ${code.split(':')[1]}`, 'warn']
  }
  if (code.startsWith('risk_escalation:')) {
    return [`Risk escalation: ${code.split(':')[1]}`, 'warn']
  }
  if (code.startsWith('signal:')) {
    const name = code.slice(7).replace(/\s*\(.*\)$/, '')
    const meta = REASON_META[name]
    return meta ? meta : [name.replace(/_/g, ' '), 'warn']
  }
  return [code.replace(/_/g, ' '), 'warn']
}

// Flatten every scenario's purchases into one queue, carrying the scenario
// (and therefore its compiled mandate) with each one.
const QUEUE = realData.scenarios.flatMap((scenario) =>
  scenario.purchases.map((purchase) => ({ scenario, purchase }))
)

function App() {
  const [queueIndex, setQueueIndex] = useState(0)
  const [stage, setStage] = useState(0)
  const [apiOnline, setApiOnline] = useState(false)
  const [liveResult, setLiveResult] = useState(null)
  const [draftInstruction, setDraftInstruction] = useState(null)
  const [pendingLive, setPendingLive] = useState(false)
  // Hold on the current purchase from the moment the operator starts typing,
  // through the round trip, and for as long as a live result is on screen.
  // `pendingLive` matters: without it the carousel advances while the fetch is
  // in flight, the answer arrives for a purchase that has already gone, and the
  // audience sees nothing. Escape clears the result and the carousel resumes.
  const paused = draftInstruction !== null || liveResult !== null || pendingLive
  // Mirrored into a ref so the interval below reads the current value without
  // being torn down and recreated on every pause change. Written in an effect,
  // not during render: a ref write during render is a side effect, and under
  // StrictMode's double render it is the kind of thing that silently goes stale.
  const pausedRef = useRef(paused)
  useEffect(() => {
    pausedRef.current = paused
  }, [paused])

  const { scenario, purchase } = QUEUE[queueIndex]

  // Is the optional live API up? If not, everything still works from the
  // generated file - the demo must never depend on a server being alive.
  useEffect(() => {
    let cancelled = false
    fetch(`${API}/api/health`)
      .then((r) => r.json())
      .then((d) => !cancelled && setApiOnline(Boolean(d.ok)))
      .catch(() => !cancelled && setApiOnline(false))
    return () => {
      cancelled = true
    }
  }, [])

  // Walk the pipeline, then move to the next real purchase.
  useEffect(() => {
    setStage(0)
    const timer = window.setInterval(() => {
      setStage((current) => {
        // Stages always run to completion, even while paused - otherwise a
        // paused screen freezes mid-pipeline with no decision shown.
        if (current < STAGES.length - 1) return current + 1
        if (pausedRef.current) return current
        setQueueIndex((i) => (i + 1) % QUEUE.length)
        return 0
      })
    }, STAGE_MS)
    return () => window.clearInterval(timer)
  }, [queueIndex])

  const runLive = useCallback(
    (instruction) => {
      if (!apiOnline) return
      setPendingLive(true)
      fetch(`${API}/api/decide`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ instruction, purchaseId: purchase.id }),
      })
        .then((r) => r.json())
        .then((d) => {
          setLiveResult(d.error ? null : d)
          setDraftInstruction(null)
        })
        .catch(() => setLiveResult(null))
        .finally(() => setPendingLive(false))
    },
    [apiOnline, purchase.id]
  )

  // The live result only applies to the purchase it was asked about.
  const live = liveResult && liveResult.purchaseId === purchase.id ? liveResult : null

  const decision = live ? live.decision : purchase.decision
  const reasonCodes = live ? live.reasonCodes : purchase.reasonCodes
  const evidence = live ? live.evidence : purchase.evidence
  const customerMessage = live ? live.customerMessage : purchase.customerMessage
  const latencyMs = live ? live.latencyMs : purchase.latencyMs
  const mandate = live ? live.mandate : scenario.mandate
  const instruction = live ? live.mandate.instruction : scenario.instruction

  const decisionVisible = stage >= STAGES.length - 1
  const deadlineMs = realData.deadlineMs
  const usedPercent = Math.min((latencyMs / deadlineMs) * 100, 100)
  // A 0.3ms decision against an 8s budget is ~0.004% - invisible. Floor the arc
  // so the ring reads as "measured and tiny", not as "broken".
  const ringPercent = Math.max(usedPercent, 1.5)
  const headroom = Math.round(deadlineMs / Math.max(latencyMs, 0.001))
  const withinSla = latencyMs <= deadlineMs

  const checks = useMemo(() => {
    const seen = new Set()
    const rows = []
    reasonCodes.forEach((code) => {
      const [title, status] = describeReason(code)
      if (seen.has(title)) return
      seen.add(title)
      const detail = evidence.find((e) =>
        e.toLowerCase().includes(code.split(':')[0].split(' ')[0].toLowerCase())
      )
      rows.push({ title, status, detail: detail || evidence[rows.length] || '' })
    })
    if (!rows.length) rows.push({ title: 'No rules matched', status: 'ok', detail: '' })
    return rows.slice(0, 4)
  }, [reasonCodes, evidence])

  const revealedChecks = stage >= 2 ? checks.length : stage >= 1 ? 1 : 0

  return (
    <div className="app-shell">
      <header className="topbar">
        <div>
          <p className="eyebrow">Wallet control layer</p>
          <h1>Agent on a Leash</h1>
        </div>
        <span className={`status-live ${apiOnline ? 'is-live' : ''}`}>
          {apiOnline ? 'Live engine' : 'Recorded run'} · {scenario.id}
        </span>
      </header>

      <section className="flow-overview panel">
        <div className="panel-header">
          <h2>Decision path</h2>
          <span className="panel-tag">{scenario.name}</span>
        </div>

        <div className="pipeline" aria-label="Decision pipeline">
          {STAGES.map((s, i) => (
            <div
              key={s.key}
              className={`pipe-stage ${i < stage ? 'done' : ''} ${i === stage ? 'current' : ''}`}
            >
              <span className="pipe-dot" />
              <span className="pipe-label">{s.label}</span>
              <span className="pipe-value">
                {s.key === 'instruction' && `${scenario.id}`}
                {s.key === 'mandate' &&
                  `${mandate.hardRules.length} rule${mandate.hardRules.length === 1 ? '' : 's'}`}
                {s.key === 'checks' && `${checks.length} signal${checks.length === 1 ? '' : 's'}`}
                {s.key === 'decision' && (decisionVisible ? OUTCOME_LABEL[decision] : '…')}
              </span>
            </div>
          ))}
          <div className={`pipe-outcome ${decisionVisible ? decision : 'pending'}`}>
            {decisionVisible ? OUTCOME_LABEL[decision] : 'Deciding'}
          </div>
        </div>
      </section>

      <main className="dashboard-grid">
        <section className="panel request-panel">
          <div className="panel-header">
            <h2>Incoming request</h2>
            <span className="panel-tag">{purchase.id}</span>
          </div>

          <div className="request-summary">
            <div className="info-row">
              <span className="label">
                Customer rule
                {apiOnline && !paused && ' — type a new rule, Enter to run it live'}
                {apiOnline && paused && ' — live result held · Esc to resume'}
              </span>
              {apiOnline ? (
                <input
                  className="rule-input"
                  value={draftInstruction === null ? instruction : draftInstruction}
                  onChange={(e) => setDraftInstruction(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      // The draft is cleared when the result lands, not here -
                      // clearing it now would unpause mid-flight.
                      runLive(e.currentTarget.value)
                    }
                    if (e.key === 'Escape') {
                      setDraftInstruction(null)
                      setLiveResult(null)
                    }
                  }}
                  spellCheck={false}
                />
              ) : (
                <strong>{instruction}</strong>
              )}
            </div>

            <div className="info-row split">
              <div>
                <span className="label">Product</span>
                <strong>{purchase.product}</strong>
              </div>
              <div>
                <span className="label">Amount</span>
                <strong>
                  {purchase.currency} {purchase.amount?.toFixed(2)}
                  {purchase.currency !== 'CHF' && (
                    <em className="converted"> → CHF {purchase.amountChf?.toFixed(2)}</em>
                  )}
                </strong>
              </div>
            </div>

            <div className="info-row split">
              <div>
                <span className="label">Merchant</span>
                <strong>
                  {purchase.merchant}
                  <em className="muted-note">
                    {' '}
                    {purchase.merchantCategory} ·{' '}
                    {purchase.merchantApprovedCount > 0
                      ? `used ${purchase.merchantApprovedCount}×`
                      : 'never used'}
                  </em>
                </strong>
              </div>
              <div>
                <span className="label">Returnable</span>
                <strong>{purchase.orderReturnable}</strong>
              </div>
            </div>

            <div className="info-row">
              <span className="label">Seller text — untrusted</span>
              <strong className="untrusted">{purchase.itemDetails || '—'}</strong>
            </div>
          </div>
        </section>

        <aside className="panel side-panel">
          <div className="timer-box">
            <div className="timer-header">
              <span>Decision latency</span>
              <span className={`sla-badge ${withinSla ? 'ok' : 'danger'}`}>
                {withinSla ? 'Within SLA' : 'Missed SLA'}
              </span>
            </div>

            <div className="timer-ring" style={{ '--progress': `${ringPercent}%` }}>
              <div className="timer-inner">
                <strong>{latencyMs < 1 ? latencyMs.toFixed(2) : latencyMs.toFixed(1)}</strong>
                <span>ms measured</span>
              </div>
            </div>

            <div className="timer-scale">
              <span>{deadlineMs / 1000}s budget</span>
              <span>{headroom.toLocaleString()}× headroom</span>
            </div>
          </div>

          <div className={`decision-box ${decisionVisible ? `decision-${decision}` : 'decision-analyzing'}`}>
            <span className="decision-label">Decision</span>
            <strong>{decisionVisible ? OUTCOME_LABEL[decision] : 'Deciding'}</strong>
          </div>
        </aside>

        <section className="panel checks-panel">
          <div className="panel-header">
            <h2>Why</h2>
            <span className="panel-tag">{reasonCodes.length} reason codes</span>
          </div>

          <div className="check-list">
            {checks.map((check, index) => {
              const isVisible = index < revealedChecks
              return (
                <div
                  key={check.title}
                  className={`check-card ${check.status} ${isVisible ? 'visible' : 'hidden'}`}
                >
                  <div className="check-topline">
                    <h3>{check.title}</h3>
                    <span className={`status-dot ${check.status}`} aria-label={check.status} />
                  </div>
                  {isVisible && check.detail && <p>{check.detail}</p>}
                </div>
              )
            })}
          </div>
        </section>

        <section className="panel response-panel">
          <div className="panel-header">
            <h2>Response back to agent</h2>
            <span className="panel-tag accent">Natural language</span>
          </div>

          <div className="response-box">
            <p>{decisionVisible ? customerMessage : 'Evaluating against the compiled mandate…'}</p>
          </div>
        </section>
      </main>
    </div>
  )
}

export default App
